spr_enemy_walk_d = sprite_add("enemy/D_Walk.png", 6, true, true, 48, 48);
spr_enemy_death_d = sprite_add("enemy/D_Death.png", 6, true, true, 48, 48);
spr_enemy_attack_d = sprite_add("enemy/D_Attack.png", 6, true, true, 48, 48);
spr_enemy_walk_s = sprite_add("enemy/S_Walk.png", 6, true, true, 48, 48);
spr_enemy_death_s = sprite_add("enemy/S_Death.png", 6, true, true, 48, 48);
spr_enemy_attack_s = sprite_add("enemy/S_Attack.png", 6, true, true, 48, 48);
spr_enemy_walk_u = sprite_add("enemy/U_Walk.png", 6, true, true, 48, 48);
spr_enemy_death_u = sprite_add("enemy/U_Death.png", 6, true, true, 48, 48);
spr_enemy_attack_u = sprite_add("enemy/U_Attack.png", 6, true, true, 48, 48);
hp = 15;
damage = 10;
sprite_set_offset(spr_enemy_walk_d, 24, 24);
sprite_set_offset(spr_enemy_walk_s, 24, 24);
sprite_set_offset(spr_enemy_walk_u, 24, 24);
sprite_set_offset(spr_enemy_attack_d, 24, 24);
sprite_set_offset(spr_enemy_attack_s, 24, 24);
sprite_set_offset(spr_enemy_attack_u, 24, 24);
sprite_set_offset(spr_enemy_death_d, 24, 24);
sprite_set_offset(spr_enemy_death_s, 24, 24);
sprite_set_offset(spr_enemy_death_u, 24, 24);
sprite_index = spr_enemy_walk_d;
image_xscale = 3;
image_yscale = 3;
image_speed = 0.5;
image_angle = 0;
sp = 4;