hp = 100;
damage = 5;
coins = 0;
sp = 4;
speed = 0;
can_shoot = true;
scale = 3;
spr_player_idle_d =  sprite_add("player/D_Idle.png", 4, true, true, 48, 48);
spr_player_walk_d = sprite_add("player/D_Walk.png", 6, true, true, 48, 48);
spr_player_special_d = sprite_add("player/D_Special.png", 6, true, true, 48, 48);
spr_player_idle_s = sprite_add("player/S_Idle.png", 4, true, true, 48, 48);
spr_player_walk_s = sprite_add("player/S_Walk.png", 6, true, true, 48, 48);
spr_player_special_s = sprite_add("player/S_Special.png", 6, true, true, 48, 48);
spr_player_idle_u = sprite_add("player/U_Idle.png", 4, true, true, 48, 48);
spr_player_walk_u = sprite_add("player/U_Walk.png", 6, true, true, 48, 48);
spr_player_special_u = sprite_add("player/U_Special.png", 6, true, true, 48, 48);
sprite_index = spr_player_idle_d;
image_xscale = scale;
image_yscale = scale;
image_speed = 0.25;
image_angle = 0;
sprite_set_offset(spr_player_idle_d, 24, 24);
sprite_set_offset(spr_player_idle_s, 24, 24);
sprite_set_offset(spr_player_idle_u, 24, 24);
sprite_set_offset(spr_player_walk_d, 24, 24);
sprite_set_offset(spr_player_walk_s, 24, 24);
sprite_set_offset(spr_player_walk_u, 24, 24);
sprite_set_offset(spr_player_special_d, 24, 24);
sprite_set_offset(spr_player_special_s, 24, 24);
sprite_set_offset(spr_player_special_u, 24, 24);
timeout = 18000;
alarm[1] = timeout;
sprite_collision_mask(spr_player_idle_d, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_idle_s, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_idle_u, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_walk_d, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_walk_u, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_walk_s, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_special_d, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_special_u, false, 0, 0, 0, 0, 0, 0, 0);
sprite_collision_mask(spr_player_special_s, false, 0, 0, 0, 0, 0, 0, 0);
//window_set_fullscreen(true);
